# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.index <- function(content, indexName) {
    .Call(`_geonamesr_index`, content, indexName)
}

.indexBulk <- function(content, indexName) {
    .Call(`_geonamesr_indexBulk`, content, indexName)
}

.search <- function(queryText, maxItems, indexName) {
    .Call(`_geonamesr_search`, queryText, maxItems, indexName)
}

